version: '2'
services:
  mysql:
    build: docker/mysql
    ports:
      - '8989:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: docker/php
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
